name: docker

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: mattipaksula
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mattipaksula/ws-doom
          tag_with_ref: true
          tag_with_sha: true
          cache_froms: mattipaksula/ws-doom:latest
        env:
          DOCKER_BUILDKIT: 1
